In [131]:
#Liður 1a

import numpy as np

data=np.load('docmatrix.npz')
X=data['X']
y=data['y']
y[y==2] = -1
y[y==3] = -1
terms=data['terms']

# Skipta í gögnum í þjálfunar- og prófunargögn
n=X.shape[0]
rnd=np.random.permutation(n) # Slembin umröðun talnanna 1,...,n
nfrac=0.7 # Hlutfall gagna sem er notað til þjálfunar
n_train=int(nfrac*n)
n_test=int(0.3*n)
x_train=X[rnd[0:n_train],:]
y_train=y[rnd[0:n_train]]
x_test=X[rnd[n_train:],:]
y_test=y[rnd[n_train:]]
#print("X_train:", x_train.shape)
#print("X_test:", x_test.shape)
#print(y_train)

A_train = np.c_[np.ones(n_train), x_train]
A_test = np.c_[np.ones(n_test), x_test]
theta,res_train,rank_train,_ = np.linalg.lstsq(A_train, y_train, rcond=False)
#print("theta_train:", theta_train) # Ekki sömu gildi og í bók


# Spá
ypred_test=np.sign(np.dot(A_test,theta))

#bera saman
print("Skekkja test gagna: ", np.sum(y_test != ypred_test)/n_test)



A_test = np.c_[np.ones(n_test), x_test]


ypred_train=np.sign(np.dot(A_train,theta))

print("Skekkja train gagnanna: ", np.sum(y_train != ypred_train)/n_train)

fylk=np.zeros(10)
the=theta.copy()
tem=terms.copy()
#Liður 1b
for i in range (0,10):
    tala=np.argmax(abs(the))
    fylk[i]=tala
    print(tem[tala])
    the[tala]=0

Skekkja test gagna:  0.044444444444444446
Skekkja train gagnanna:  0.002380952380952381
harri
head
climb
grow
long
risk
plan
hagrid
complet
isra


In [74]:
#Liður 2a (prufa hjá mér, notum ekki)

import numpy as np

data=np.load('mnist_small.npz')
x_train=data['x_train']
y_train=data['y_train']
x_test=data['x_test']
y_test=data['y_test']
n_train = len(y_train)
n_test = len(y_test)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)



y=np.array([y_train, y_train, y_train, y_train, y_train, y_train, y_train, y_train, y_train, y_train, y_train])
y2=np.array([y_test, y_test, y_test, y_test, y_test, y_test, y_test, y_test, y_test, y_test])

count=np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
thetaFylki=np.array([])

def thjalfun(y_train, y_test):
    theta_train,res_train,rank_train,_ = np.linalg.lstsq(x_train, y_train, rcond=False)
    ypred_train=np.sign(np.dot(x_test,theta_train))
    return np.sum(y_test != ypred_train)/n_test



for i in range(0, 10):
    y_train[y_train==i]=1
    y_train[y_train!=i]=-1
    y_test[y_test==i]=1
    y_test[y_test!=i]=-1
    
    count[i] = thjalfun(y_train, y_test)
    y_train = y[i]
    y_test = y2[i]


print(count)
print(thetaFylki)


(10000, 784)
(10000,)
(1000, 784)
(1000,)
[0.003 0.027 0.003 0.003 0.003 0.003 0.003 0.003 0.003 0.003]
[]


In [132]:
#Liður 2a (notast við þetta)

import numpy as np

data=np.load('mnist_small.npz')
x_train=data['x_train']
y_train=data['y_train']
x_test=data['x_test']
y_test=data['y_test']
n_train = len(y_train)
n_test = len(y_test)


print(y_train)
#i=0
y_0 = y_train.copy()
y_0test=y_test.copy()
y_0[y_0!=0]=-1
y_0[y_0==0]=1
y_0test[y_0test!=0]=-1
y_0test[y_0test==0]=1

theta0,res_train0,rank_train0,_ = np.linalg.lstsq(x_train, y_0, rcond=False)
ypred0=np.sign(np.dot(x_test,theta0))
villutidni0 = np.sum(y_0test != ypred0)/n_test

print()
print("villutíðni fyrir i=0: ",villutidni0)
print(y_0)

#i=1
y_1 = y_train.copy()
y_1test=y_test.copy()
y_1[y_1!=1]=-1
y_1[y_1==1]=1
y_1test[y_1test!=1]=-1
y_1test[y_1test==1]=1

theta1,res_train1,rank_train1,_ = np.linalg.lstsq(x_train, y_1, rcond=False)
ypred1=np.sign(np.dot(x_test,theta1))
villutidni1 = np.sum(y_1test != ypred1)/n_test

print()
print(villutidni1)
print(y_1)


#i=2
y_2 = y_train.copy()
y_2test=y_test.copy()
y_2[y_2!=2]=-1
y_2[y_2==2]=1
y_2test[y_2test!=2]=-1
y_2test[y_2test==2]=1

theta2,res_train2,rank_train2,_ = np.linalg.lstsq(x_train, y_2, rcond=False)
ypred2=np.sign(np.dot(x_test,theta2))
villutidni2 = np.sum(y_2test != ypred2)/n_test

print()
print(villutidni2)
print(y_2)


#i=3
y_3 = y_train.copy()
y_3test=y_test.copy()
y_3[y_3!=3]=-1
y_3[y_3==3]=1
y_3test[y_3test!=3]=-1
y_3test[y_3test==3]=1

theta3,res_train3,rank_train3,_ = np.linalg.lstsq(x_train, y_3, rcond=False)
ypred3=np.sign(np.dot(x_test,theta3))
villutidni3 = np.sum(y_3test != ypred3)/n_test

print()
print(villutidni3)
print(y_3)

#i=4
y_4 = y_train.copy()
y_4test=y_test.copy()
y_4[y_4!=4]=-1
y_4[y_4==4]=1
y_4test[y_4test!=4]=-1
y_4test[y_4test==4]=1


theta4,res_train4,rank_train4,_ = np.linalg.lstsq(x_train, y_4, rcond=False)
ypred4=np.sign(np.dot(x_test,theta4))
villutidni4 = np.sum(y_4test != ypred4)/n_test

print()
print(villutidni4)
print(y_4)

#i=5
y_5 = y_train.copy()
y_5test=y_test.copy()
y_5[y_5!=5]=-1
y_5[y_5==5]=1
y_5test[y_5test!=5]=-1
y_5test[y_5test==5]=1


theta5,res_train5,rank_train5,_ = np.linalg.lstsq(x_train, y_5, rcond=False)
ypred5=np.sign(np.dot(x_test,theta5))
villutidni5 = np.sum(y_5test != ypred5)/n_test

print()
print(villutidni5)
print(y_5)


#i=6
y_6 = y_train.copy()
y_6test=y_test.copy()
y_6[y_6!=6]=-1
y_6[y_6==6]=1
y_6test[y_6test!=6]=-1
y_6test[y_6test==6]=1


theta6,res_train6,rank_train6,_ = np.linalg.lstsq(x_train, y_6, rcond=False)
ypred6=np.sign(np.dot(x_test,theta6))
villutidni6 = np.sum(y_6test != ypred6)/n_test

print()
print(villutidni6)
print(y_6)



#i=7
y_7 = y_train.copy()
y_7test=y_test.copy()
y_7[y_7!=7]=-1
y_7[y_7==7]=1
y_7test[y_7test!=7]=-1
y_7test[y_7test==7]=1

theta7,res_train7,rank_train7,_ = np.linalg.lstsq(x_train, y_7, rcond=False)
ypred7=np.sign(np.dot(x_test,theta7))
villutidni7 = np.sum(y_7test != ypred7)/n_test

print()
print(villutidni7)
print(y_7)



#i=8
y_8 = y_train.copy()
y_8test=y_test.copy()
y_8[y_8!=8]=-1
y_8[y_8==8]=1
y_8test[y_8test!=8]=-1
y_8test[y_8test==8]=1

theta8,res_train8,rank_train8,_ = np.linalg.lstsq(x_train, y_8, rcond=False)
ypred8=np.sign(np.dot(x_test,theta8))
villutidni8 = np.sum(y_8test != ypred8)/n_test

print()
print(villutidni8)
print(y_8)



#i=9
y_9 = y_train.copy()
y_9test=y_test.copy()
y_9[y_9!=9]=-1
y_9[y_9==9]=1
y_9test[y_9test!=9]=-1
y_9test[y_9test==9]=1

theta9,res_train9,rank_train9,_ = np.linalg.lstsq(x_train, y_9, rcond=False)
ypred9=np.sign(np.dot(x_test,theta9))
villutidni9 = np.sum(y_9test != ypred9)/n_test

print()
print(villutidni9)
print(y_9)


#fjölþátta flokkari
fjol=np.array([theta0, theta1, theta2, theta3, theta4, theta5, theta6, theta7, theta8, theta9])
print(fjol.shape)


a=np.zeros(1000)
d=np.zeros(10000)
xnyr = x_test.copy()

kp=np.transpose(fjol)

xkp=np.dot(xnyr, kp)
#print(xkp)
#print(xkp.shape)
#print()

xnyr2 = x_train.copy()
xkp2=np.dot(xnyr2, kp)

teljari = 999
teljari2 = 9999



for i in range (0,1000):
    temp, xkp = xkp[-1], xkp[:-1]
    #temp = np.array([xkp[teljari], xkp[teljari+1], xkp[teljari+2], xkp[teljari+3], xkp[teljari+4], xkp[teljari+5], xkp[teljari+6], xkp[teljari+7], xkp[teljari+8], xkp[teljari+9]])
    temp2 = temp.copy()
    b=np.argmax(temp2)
    #print(b)
    a[teljari]=b
    teljari = teljari-1
print()    
print("Villa test: ",np.sum(a != y_test)/n_test)

for i in range (0,10000):
    temp3, xkp2=xkp2[-1], xkp2[:-1]
    temp4=temp3.copy()
    c=np.argmax(temp4)
    d[teljari2]=c
    teljari2=teljari2-1
#print(a)
#print(y_test)

print()
print("villa train: ", np.sum(d != y_train)/n_train)

import pandas as pd
y_actu=pd.Series([y_test], name='Actual')
y_pred=pd.Series([a], name='Predicted')
df_confusion = pd.crosstab(y_actu, y_pred, rownames=['Actual'], colnames=['Predicted'], margins=True)
print(df_confusion)

[5. 0. 4. ... 6. 9. 7.]

villutíðni fyrir i=0:  0.016
[-1.  1. -1. ... -1. -1. -1.]

0.027
[-1. -1. -1. ... -1. -1. -1.]

0.058
[-1. -1. -1. ... -1. -1. -1.]

0.059
[-1. -1. -1. ... -1. -1. -1.]

0.036
[-1. -1.  1. ... -1. -1. -1.]

0.066
[ 1. -1. -1. ... -1. -1. -1.]

0.033
[-1. -1. -1. ...  1. -1. -1.]

0.039
[-1. -1. -1. ... -1. -1.  1.]

0.085
[-1. -1. -1. ... -1. -1. -1.]

0.065
[-1. -1. -1. ... -1.  1. -1.]
(10, 784)

Villa test:  0.205

villa train:  0.1234


TypeError: unhashable type: 'numpy.ndarray'

In [88]:
count = 5
for i in range (0,5):
    print(count)
    count = count -1

import numpy as np

a = np.zeros(50)
print(a)

b = np.array([])

5
4
3
2
1
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]
