In [131]:
#Liður 1a

import numpy as np

data=np.load('docmatrix.npz')
X=data['X']
y=data['y']
y[y==2] = -1
y[y==3] = -1
terms=data['terms']

# Skipta í gögnum í þjálfunar- og prófunargögn
n=X.shape[0]
rnd=np.random.permutation(n) # Slembin umröðun talnanna 1,...,n
nfrac=0.7 # Hlutfall gagna sem er notað til þjálfunar
n_train=int(nfrac*n)
n_test=int(0.3*n)
x_train=X[rnd[0:n_train],:]
y_train=y[rnd[0:n_train]]
x_test=X[rnd[n_train:],:]
y_test=y[rnd[n_train:]]


#Finna skekkju test gagna
A_train = np.c_[np.ones(n_train), x_train]
A_test = np.c_[np.ones(n_test), x_test]
theta,res_train,rank_train,_ = np.linalg.lstsq(A_train, y_train, rcond=False)
#spáin
ypred_test=np.sign(np.dot(A_test,theta))
#bera saman
print("Skekkja test gagna: ", np.sum(y_test != ypred_test)/n_test)


#Finna skekkju train gagna
A_test = np.c_[np.ones(n_test), x_test]
#spáin
ypred_train=np.sign(np.dot(A_train,theta))
#bera saman
print("Skekkja train gagnanna: ", np.sum(y_train != ypred_train)/n_train)



#Liður 1b

fylk=np.zeros(10)
the=theta.copy()
tem=terms.copy()
print()
print("Þau tíu orð sem hafa mest áhrif á flokkunina: ")
for i in range (0,10):
    tala=np.argmax(abs(the))
    fylk[i]=tala
    print(tem[tala])
    the[tala]=0

Skekkja test gagna:  0.044444444444444446
Skekkja train gagnanna:  0.002380952380952381
harri
head
climb
grow
long
risk
plan
hagrid
complet
isra


In [164]:
#Liður 2a

import numpy as np

data=np.load('mnist_small.npz')
x_train=data['x_train']
y_train=data['y_train']
x_test=data['x_test']
y_test=data['y_test']
n_train = len(y_train)
n_test = len(y_test)


#Búum til i=10 tvíþáttaflokkara og finnum villutíðni þeirrra á prófunargögnum

#i=0
y_0 = y_train.copy()
y_0test=y_test.copy()
y_0[y_0!=0]=-1
y_0[y_0==0]=1
y_0test[y_0test!=0]=-1
y_0test[y_0test==0]=1

theta0,res_train0,rank_train0,_ = np.linalg.lstsq(x_train, y_0, rcond=False)
ypred0=np.sign(np.dot(x_test,theta0))
villutidni0 = np.sum(y_0test != ypred0)/n_test

print("Villutíðni á prófunargögnum fyrir i=0: ",villutidni0)


#i=1
y_1 = y_train.copy()
y_1test=y_test.copy()
y_1[y_1!=1]=-1
y_1[y_1==1]=1
y_1test[y_1test!=1]=-1
y_1test[y_1test==1]=1

theta1,res_train1,rank_train1,_ = np.linalg.lstsq(x_train, y_1, rcond=False)
ypred1=np.sign(np.dot(x_test,theta1))
villutidni1 = np.sum(y_1test != ypred1)/n_test

print()
print("Villutíðni á prófunargögnum fyrir i=1: ",villutidni1)



#i=2
y_2 = y_train.copy()
y_2test=y_test.copy()
y_2[y_2!=2]=-1
y_2[y_2==2]=1
y_2test[y_2test!=2]=-1
y_2test[y_2test==2]=1

theta2,res_train2,rank_train2,_ = np.linalg.lstsq(x_train, y_2, rcond=False)
ypred2=np.sign(np.dot(x_test,theta2))
villutidni2 = np.sum(y_2test != ypred2)/n_test

print()
print("Villutíðni á prófunargögnum fyrir i=2: ",villutidni2)



#i=3
y_3 = y_train.copy()
y_3test=y_test.copy()
y_3[y_3!=3]=-1
y_3[y_3==3]=1
y_3test[y_3test!=3]=-1
y_3test[y_3test==3]=1

theta3,res_train3,rank_train3,_ = np.linalg.lstsq(x_train, y_3, rcond=False)
ypred3=np.sign(np.dot(x_test,theta3))
villutidni3 = np.sum(y_3test != ypred3)/n_test

print()
print("Villutíðni á prófunargögnum fyrir i=3: ",villutidni3)


#i=4
y_4 = y_train.copy()
y_4test=y_test.copy()
y_4[y_4!=4]=-1
y_4[y_4==4]=1
y_4test[y_4test!=4]=-1
y_4test[y_4test==4]=1


theta4,res_train4,rank_train4,_ = np.linalg.lstsq(x_train, y_4, rcond=False)
ypred4=np.sign(np.dot(x_test,theta4))
villutidni4 = np.sum(y_4test != ypred4)/n_test

print()
print("Villutíðni á prófunargögnum fyrir i=4: ",villutidni4)


#i=5
y_5 = y_train.copy()
y_5test=y_test.copy()
y_5[y_5!=5]=-1
y_5[y_5==5]=1
y_5test[y_5test!=5]=-1
y_5test[y_5test==5]=1


theta5,res_train5,rank_train5,_ = np.linalg.lstsq(x_train, y_5, rcond=False)
ypred5=np.sign(np.dot(x_test,theta5))
villutidni5 = np.sum(y_5test != ypred5)/n_test

print()
print("Villutíðni á prófunargögnum fyrir i=5: ",villutidni5)



#i=6
y_6 = y_train.copy()
y_6test=y_test.copy()
y_6[y_6!=6]=-1
y_6[y_6==6]=1
y_6test[y_6test!=6]=-1
y_6test[y_6test==6]=1


theta6,res_train6,rank_train6,_ = np.linalg.lstsq(x_train, y_6, rcond=False)
ypred6=np.sign(np.dot(x_test,theta6))
villutidni6 = np.sum(y_6test != ypred6)/n_test

print()
print("Villutíðni á prófunargögnum fyrir i=6: ",villutidni6)




#i=7
y_7 = y_train.copy()
y_7test=y_test.copy()
y_7[y_7!=7]=-1
y_7[y_7==7]=1
y_7test[y_7test!=7]=-1
y_7test[y_7test==7]=1

theta7,res_train7,rank_train7,_ = np.linalg.lstsq(x_train, y_7, rcond=False)
ypred7=np.sign(np.dot(x_test,theta7))
villutidni7 = np.sum(y_7test != ypred7)/n_test

print()
print("Villutíðni á prófunargögnum fyrir i=7: ",villutidni7)




#i=8
y_8 = y_train.copy()
y_8test=y_test.copy()
y_8[y_8!=8]=-1
y_8[y_8==8]=1
y_8test[y_8test!=8]=-1
y_8test[y_8test==8]=1

theta8,res_train8,rank_train8,_ = np.linalg.lstsq(x_train, y_8, rcond=False)
ypred8=np.sign(np.dot(x_test,theta8))
villutidni8 = np.sum(y_8test != ypred8)/n_test

print()
print("Villutíðni á prófunargögnum fyrir i=8: ",villutidni8)




#i=9
y_9 = y_train.copy()
y_9test=y_test.copy()
y_9[y_9!=9]=-1
y_9[y_9==9]=1
y_9test[y_9test!=9]=-1
y_9test[y_9test==9]=1

theta9,res_train9,rank_train9,_ = np.linalg.lstsq(x_train, y_9, rcond=False)
ypred9=np.sign(np.dot(x_test,theta9))
villutidni9 = np.sum(y_9test != ypred9)/n_test

print()
print("Villutíðni á prófunargögnum fyrir i=9: ",villutidni9)



#fjölþátta flokkari
fjol=np.array([theta0, theta1, theta2, theta3, theta4, theta5, theta6, theta7, theta8, theta9])
print(fjol.shape)


#byltum fjölþáttaflokkaranum og búum til tvö fylki, annað er fjölþ.fl. byltur sinnum x_test(xkp),
#hitt er fjölþ.fl. byltur sinnum x_train (xkp2)
a=np.zeros(1000)
d=np.zeros(10000)
xnyr = x_test.copy()

kp=np.transpose(fjol)

xkp=np.dot(xnyr, kp)


xnyr2 = x_train.copy()
xkp2=np.dot(xnyr2, kp)

teljari = 999
teljari2 = 9999


#Finnum svo villutíðni fyrir prófunargögn

for i in range (0,1000):
    temp, xkp = xkp[-1], xkp[:-1]
    #temp = np.array([xkp[teljari], xkp[teljari+1], xkp[teljari+2], xkp[teljari+3], xkp[teljari+4], xkp[teljari+5], xkp[teljari+6], xkp[teljari+7], xkp[teljari+8], xkp[teljari+9]])
    temp2 = temp.copy()
    b=np.argmax(temp2)
    #print(b)
    a[teljari]=b
    teljari = teljari-1
print()    
print("Villutíðni prófunargagna: ",np.sum(a != y_test)/n_test)


#Finnum villutíðni þjálfunargagna

for i in range (0,10000):
    temp3, xkp2=xkp2[-1], xkp2[:-1]
    temp4=temp3.copy()
    c=np.argmax(temp4)
    d[teljari2]=c
    teljari2=teljari2-1


print()
print("Villutíðni þjálfunargagna: ", np.sum(d != y_train)/n_train)
print()
print()




#Liður 2c

#Búum til fall sem bætir við q nýjum breytum við fyrir hverja mynd í prófunargögnum

def test(q):
    hal=np.zeros(q)
    loka=np.zeros(q+784)

    xr = x_test.copy()
    for i in range (0,1000):
        temp, xr = xr[-1], xr[:-1]
        R=np.random.randint(-1,1, size=(q, 784))
        R[R==0]=1
        Rx = np.dot(R, temp)
        Rxnytt = np.maximum(Rx,hal)
        Rxnytt=np.append(temp,Rxnytt)
        loka = np.c_[Rxnytt, loka]

    loka = np.transpose(loka)
    bull, loka = loka[-1], loka[:-1]
    return loka

#Búum til nýju prófunargögnin fyrir öll q

fylki100=test(100)
print("test, q=100: ",fylki100.shape)
fylki1000=test(1000)
#print("lokafylki test: ",fylki1000)
print("test, q=1000: ",fylki1000.shape)
fylki5000=test(5000)
#print("lokafylki test: ",fylki5000)
print("test, q=5000: ",fylki5000.shape)
fylki10000=test(10000)
#print("lokafylki test: ",fylki10000)
print("test, q=10000: ",fylki10000.shape)

        












[5. 0. 4. ... 6. 9. 7.]

villutíðni fyrir i=0:  0.016
[-1.  1. -1. ... -1. -1. -1.]

0.027
[-1. -1. -1. ... -1. -1. -1.]

0.058
[-1. -1. -1. ... -1. -1. -1.]

0.059
[-1. -1. -1. ... -1. -1. -1.]

0.036
[-1. -1.  1. ... -1. -1. -1.]

0.066
[ 1. -1. -1. ... -1. -1. -1.]

0.033
[-1. -1. -1. ...  1. -1. -1.]

0.039
[-1. -1. -1. ... -1. -1.  1.]

0.085
[-1. -1. -1. ... -1. -1. -1.]

0.065
[-1. -1. -1. ... -1.  1. -1.]
(10, 784)

Villa test:  0.205

villa train:  0.1234


lokafylki test:  [[   0.    0.    0. ...    0.  496.  582.]
 [   0.    0.    0. ...  280.  700. 3754.]
 [   0.    0.    0. ...  831.    0. 1063.]
 ...
 [   0.    0.    0. ...    0.    0.    0.]
 [   0.    0.    0. ...    0. 3195.    0.]
 [   0.    0.    0. ...  151.    0. 1615.]]
(1000, 1784)
lokafylki test:  [[   0.    0.    0. ... 1228. 2780.    0.]
 [   0.    0.    0. ... 2474. 2118.  340.]
 [   0.    0.    0. ...    0.    0.  893.]
 ...
 [   0.    0.    0. ...    0. 6334.    0.]
 [   0.    0.    0. ...    0.    0.    0.

In [171]:
#Liður 2c, framhald

#Búum til fall sem bætir við q nýjum breytum við fyrir hverja mynd í þjálfunargögnunum

def train(q):
    hal=np.zeros(q)
    loka=np.zeros(q+784)

    xr = x_train.copy()
    for i in range (0,10000):
        temp, xr = xr[-1], xr[:-1]
        R=np.random.randint(-1,1, size=(q, 784))
        R[R==0]=1
        Rx = np.dot(R, temp)
        Rxnytt = np.maximum(Rx,hal)
        Rxnytt=np.append(temp,Rxnytt)
        loka = np.c_[Rxnytt, loka]

    loka = np.transpose(loka)
    bull, loka = loka[-1], loka[:-1]
    return loka

#Búum til nýju þjálfunargögnin fyrir öll q

fylki100_train=train(100)
print("train, q=100: ",fylki100_train.shape)
fylki1000_train=train(1000)
print("train, q=1000: ",fylki1000_train.shape)
fylki5000_train=train(5000)
print("train, q=5000: ",fylki5000_train.shape)
fylki10000_train=train(10000)
print("train, q=10000: ",fylki10000_train.shape)


(10000, 884)
(10000, 1784)
(10000, 5784)
(10000, 10784)


In [ ]:
print("klar parat")
print("byrjað að keyra")

#i=0
theta00,res_train00,rank_train00,_=np.linalg.lstsq(fylki100_train, y_0, rcond=False)
#ypred00=np.sign(np.dot(fylki100,theta00))
#villutidni00=np.sum(y_0test != ypred00)/ntest

theta01,res_train01,rank_train01,_=np.linalg.lstsq(fylki1000_train, y_0, rcond=False)
#ypred01=np.sign(np.dot(fylki1000,theta01))
#villutidni01=np.sum(y_0test != ypred01)/ntest

theta02,res_train02,rank_train02,_=np.linalg.lstsq(fylki5000_train, y_0, rcond=False)
#ypred02=np.sign(np.dot(fylki5000,theta02))
#villutidni02=np.sum(y_0test != ypred02)/ntest

theta03,res_train03,rank_train03,_=np.linalg.lstsq(fylki10000_train, y_0, rcond=False)
#ypred03=np.sign(np.dot(fylki10000,theta03))
#villutidni03=np.sum(y_0test != ypred03)/ntest

print("áfangi 0")

#i=1
theta10,res_train10,rank_train10,_=np.linalg.lstsq(fylki100_train, y_1, rcond=False)
#ypred10=np.sign(np.dot(fylki100,theta10))
#villutidni10=np.sum(y_1test != ypred10)/ntest

theta11,res_train11,rank_train11,_=np.linalg.lstsq(fylki1000_train, y_1, rcond=False)
#ypred11=np.sign(np.dot(fylki1000,theta11))
#villutidni11=np.sum(y_1test != ypred11)/ntest

theta12,res_train12,rank_train12,_=np.linalg.lstsq(fylki5000_train, y_1, rcond=False)
#ypred12=np.sign(np.dot(fylki5000,theta12))
#villutidni12=np.sum(y_1test != ypred12)/ntest

theta13,res_train13,rank_train13,_=np.linalg.lstsq(fylki10000_train, y_1, rcond=False)
#ypred13=np.sign(np.dot(fylki10000,theta13))
#villutidni13=np.sum(y_1test != ypred13)/ntest


#i=2
theta20,res_train20,rank_train20,_=np.linalg.lstsq(fylki100_train, y_2, rcond=False)
#ypred20=np.sign(np.dot(fylki100,theta20))
#villutidni20=np.sum(y_2test != ypred20)/ntest

theta21,res_train21,rank_train21,_=np.linalg.lstsq(fylki1000_train, y_2, rcond=False)
#ypred21=np.sign(np.dot(fylki1000,theta21))
#villutidni21=np.sum(y_2test != ypred21)/ntest

theta22,res_train22,rank_train22,_=np.linalg.lstsq(fylki5000_train, y_2, rcond=False)
#ypred22=np.sign(np.dot(fylki5000,theta22))
#villutidni22=np.sum(y_2test != ypred22)/ntest

theta23,res_train23,rank_train23,_=np.linalg.lstsq(fylki10000_train, y_2, rcond=False)
#ypred23=np.sign(np.dot(fylki10000,theta23))
#villutidni23=np.sum(y_2test != ypred23)/ntest

print("áfangi 1")

#i=3
theta30,res_train30,rank_train30,_=np.linalg.lstsq(fylki100_train, y_3, rcond=False)
#ypred30=np.sign(np.dot(fylki100,theta30))
#villutidni30=np.sum(y_3test != ypred30)/ntest

theta31,res_train31,rank_train31,_=np.linalg.lstsq(fylki1000_train, y_3, rcond=False)
#ypred31=np.sign(np.dot(fylki1000,theta31))
#villutidni31=np.sum(y_3test != ypred31)/ntest

theta32,res_train32,rank_train32,_=np.linalg.lstsq(fylki5000_train, y_3, rcond=False)
#ypred32=np.sign(np.dot(fylki5000,theta32))
#villutidni32=np.sum(y_3test != ypred32)/ntest

theta33,res_train33,rank_train33,_=np.linalg.lstsq(fylki10000_train, y_3, rcond=False)
#ypred33=np.sign(np.dot(fylki10000,theta33))
#villutidni33=np.sum(y_3test != ypred33)/ntest



#i=4
theta40,res_train40,rank_train40,_=np.linalg.lstsq(fylki100_train, y_4, rcond=False)
#ypred40=np.sign(np.dot(fylki100,theta40))
#villutidni40=np.sum(y_4test != ypred40)/ntest

theta41,res_train41,rank_train41,_=np.linalg.lstsq(fylki1000_train, y_4, rcond=False)
#ypred41=np.sign(np.dot(fylki1000,theta41))
#villutidni41=np.sum(y_4test != ypred41)/ntest

theta42,res_train42,rank_train42,_=np.linalg.lstsq(fylki5000_train, y_4, rcond=False)
#ypred42=np.sign(np.dot(fylki5000,theta42))
#villutidni42=np.sum(y_4test != ypred42)/ntest

theta43,res_train43,rank_train43,_=np.linalg.lstsq(fylki10000_train, y_4, rcond=False)
#ypred43=np.sign(np.dot(fylki10000,theta43))
#villutidni43=np.sum(y_4test != ypred43)/ntest

Print("áfangi 2")

#i=5
theta50,res_train50,rank_train50,_=np.linalg.lstsq(fylki100_train, y_5, rcond=False)
#ypred50=np.sign(np.dot(fylki100,theta50))
#villutidni50=np.sum(y_5test != ypred50)/ntest

theta51,res_train51,rank_train51,_=np.linalg.lstsq(fylki1000_train, y_5, rcond=False)
#ypred51=np.sign(np.dot(fylki1000,theta51))
#villutidni51=np.sum(y_5test != ypred51)/ntest

theta52,res_train52,rank_train52,_=np.linalg.lstsq(fylki5000_train, y_5, rcond=False)
#ypred52=np.sign(np.dot(fylki5000,theta52))
#villutidni52=np.sum(y_5test != ypred52)/ntest

theta53,res_train53,rank_train53,_=np.linalg.lstsq(fylki10000_train, y_5, rcond=False)
#ypred53=np.sign(np.dot(fylki10000,theta53))
#villutidni53=np.sum(y_5test != ypred53)/ntest



#i=6
theta60,res_train60,rank_train60,_=np.linalg.lstsq(fylki100_train, y_6, rcond=False)
#ypred60=np.sign(np.dot(fylki100,theta60))
#villutidni60=np.sum(y_6test != ypred60)/ntest

theta61,res_train61,rank_train61,_=np.linalg.lstsq(fylki1000_train, y_6, rcond=False)
#ypred61=np.sign(np.dot(fylki1000,theta61))
#villutidni61=np.sum(y_6test != ypred61)/ntest

theta62,res_train62,rank_train62,_=np.linalg.lstsq(fylki5000_train, y_6, rcond=False)
#ypred62=np.sign(np.dot(fylki5000,theta62))
#villutidni62=np.sum(y_6test != ypred62)/ntest

theta63,res_train63,rank_train63,_=np.linalg.lstsq(fylki10000_train, y_6, rcond=False)
#ypred63=np.sign(np.dot(fylki10000,theta63))
#villutidni63=np.sum(y_6test != ypred63)/ntest



#i=7
theta70,res_train70,rank_train70,_=np.linalg.lstsq(fylki100_train, y_7, rcond=False)
#ypred70=np.sign(np.dot(fylki100,theta70))
#villutidni70=np.sum(y_7test != ypred70)/ntest

theta71,res_train71,rank_train71,_=np.linalg.lstsq(fylki1000_train, y_7, rcond=False)
#ypred71=np.sign(np.dot(fylki1000,theta71))
#villutidni71=np.sum(y_7test != ypred71)/ntest

theta72,res_train72,rank_train72,_=np.linalg.lstsq(fylki5000_train, y_7, rcond=False)
#ypred72=np.sign(np.dot(fylki5000,theta72))
#villutidni72=np.sum(y_7test != ypred72)/ntest

theta73,res_train73,rank_train73,_=np.linalg.lstsq(fylki10000_train, y_7, rcond=False)
#ypred73=np.sign(np.dot(fylki10000,theta73))
#villutidni73=np.sum(y_7test != ypred73)/ntest



#i=8
theta80,res_train80,rank_train80,_=np.linalg.lstsq(fylki100_train, y_8, rcond=False)
#ypred80=np.sign(np.dot(fylki100,theta80))
#villutidni80=np.sum(y_8test != ypred80)/ntest

theta81,res_train81,rank_train81,_=np.linalg.lstsq(fylki1000_train, y_8, rcond=False)
#ypred81=np.sign(np.dot(fylki1000,theta81))
#villutidni81=np.sum(y_8test != ypred81)/ntest

theta82,res_train82,rank_train82,_=np.linalg.lstsq(fylki5000_train, y_8, rcond=False)
#ypred82=np.sign(np.dot(fylki5000,theta82))
#villutidni82=np.sum(y_8test != ypred82)/ntest

theta83,res_train83,rank_train83,_=np.linalg.lstsq(fylki10000_train, y_8, rcond=False)
#ypred83=np.sign(np.dot(fylki10000,theta83))
#villutidni83=np.sum(y_8test != ypred83)/ntest



#i=9
theta90,res_train90,rank_train90,_=np.linalg.lstsq(fylki100_train, y_9, rcond=False)
#ypred90=np.sign(np.dot(fylki100,theta90))
#villutidni90=np.sum(y_9test != ypred90)/ntest

theta91,res_train91,rank_train91,_=np.linalg.lstsq(fylki1000_train, y_9, rcond=False)
#ypred91=np.sign(np.dot(fylki1000,theta91))
#villutidni91=np.sum(y_9test != ypred91)/ntest

theta92,res_train92,rank_train92,_=np.linalg.lstsq(fylki5000_train, y_9, rcond=False)
#ypred92=np.sign(np.dot(fylki5000,theta92))
#villutidni92=np.sum(y_9test != ypred92)/ntest

theta93,res_train93,rank_train93,_=np.linalg.lstsq(fylki10000_train, y_9, rcond=False)
#ypred93=np.sign(np.dot(fylki10000,theta93))
#villutidni93=np.sum(y_9test != ypred93)/ntest

print("áfangi 3")
hund=np.array([theta00, theta10, theta20, theta30, theta40, theta50, theta60, theta70, theta80, theta90])
thus=np.array([theta01, theta11, theta21, theta31, theta41, theta51, theta61, theta71, theta81, theta91])
fimm=np.array([theta02, theta12, theta22, theta32, theta42, theta52, theta62, theta72, theta82, theta92])
tiu=np.array([theta03, theta13, theta23, theta33, theta43, theta53, theta63, theta73, theta83, theta93])


zero=np.zeros(1000)
uno=np.zeros(1000)
dos=np.zeros(1000)
tres=np.zeros(1000)


kp0=np.transpose(hund)
kp1=np.transpose(thus)
kp2=np.transpose(fimm)
kp3=np.transpose(tiu)

xkpzero=np.dot(fylki100, kp0)
xkpuno=np.dot(fylki1000, kp1)
xkpdos=np.dot(fylki5000, kp2)
xkptres=np.dot(fylki10000, kp3)

print("áfangi 4")

def villut(xp, nullfylki):
    counting=999
    for i in range (0,1000):
        tempzero, xp = xp[-1], xp[:-1]
        tempuno = tempzero.copy()
        b=np.argmax(tempuno)
        nullfylki[teljari]=b
        counting = counting-1
    return np.sum(nullfylki != y_test)/n_test
        
villa100=villut(xkpzero, zero)
villa1000=villut(xkpuno, uno)
print("áfangi 5")
villa5000=villut(xkpdos, dos)
villa10000=villut(xkptres, tres)

print("Villutíðni fyrir q=100: ",villa100)
print("Villutíðni fyrir q=1000: ",villa1000)
print("Villutíðni fyrir q=5000: ",villa5000)
print("Villutíðni fyrir q=10000: ",villa10000)



In [ ]:
#Liður 2d

import math


#Búum til föll til að bæta við x_test og x_train

eininga=np.identity(1000)
crap=np.zeros((1000,784))

def falltest (lamb):
    lambid=math.sqrt(lamb)
    crap[crap!=lambid]=lambid
    einlamb=np.dot(eininga, crap)
    xcrap=x_test.copy()
    lambxtest=np.concatenate((xcrap, einlamb),axis=0)
    return lambxtest

eininga2=np.identity(10000)
crap2=np.zeros((10000,784))

def falltrain (lamb):
    lambi=math.sqrt(lambi)
    crap2[crap2!=lambi]=lambi
    einlamb2=np.dot(eininga2, crap2)
    xcrap_train=x_train.copy()
    lambxtrain=np.concatenate((xcrap_train, einlamb2),axis=0)
    return lambxtrain


#búum til nýju gögnin fyrir öll lambda gildin

nullfylki1000=np.zeros(1000)
nullfylki10000=np.zeros(10000)


lambda0test=falltest(0.01)
lambda0train=falltrain(0.01)

ytestcopy0=y_test.copy()
ytraincopy0=y_train.copy()
ylambtest0=concatenate((ytestcopy0, nullfylki1000),axis=0)
ylambtrain0=concatenate((ytraincopy0, nullfylki10000),axis=0)



lambda1test=falltest(1)
lambda1train=falltrain(1)

ytestcopy1=y_test.copy()
ytraincopy1=y_train.copy()
ylambtest1=concatenate((ytestcopy1, nullfylki1000),axis=0)
ylambtrain1=concatenate((ytraincopy1, nullfylki10000),axis=0)



lambda2test=falltest(100)
lambda2train=falltrain(100)

ytestcopy2=y_test.copy()
ytraincopy2=y_train.copy()
ylambtest2=concatenate((ytestcopy2, nullfylki1000),axis=0)
ylambtrain2=concatenate((ytraincopy2, nullfylki10000),axis=0)



lambda3test=falltest(10000)
lambda3train=falltrain(10000)

ytestcopy3=y_test.copy()
ytraincopy3=y_train.copy()
ylambtest3=concatenate((ytestcopy3, nullfylki1000),axis=0)
ylambtrain3=concatenate((ytraincopy3, nullfylki10000),axis=0)



lambda4test=falltest(1000000)
lambda4train=falltrain(1000000)

ytestcopy4=y_test.copy()
ytraincopy4=y_train.copy()
ylambtest4=concatenate((ytestcopy4, nullfylki1000),axis=0)
ylambtrain4=concatenate((ytraincopy4, nullfylki10000),axis=0)

#Finna þjálfunar- og prófunarskekkju fyrir hvert lambdagildi


